zeppelin:
  image: dylanmei/zeppelin:latest
  container_name: zeppelin
  environment:
    ZEPPELIN_PORT: 8080
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    SPARK_HOME: /usr/spark
    SPARK_SUBMIT_OPTIONS: >-
      --packages com.databricks:spark-csv_2.10:1.2.0
    MASTER: spark://spark-master-0:7077
  ports:
    - 8080:8080
    - 8081:8081
  volumes:
    - ./data:/zeppelin/data
    - ./notebooks:/zeppelin/notebook
