node:
    build: .
    environment:
        ZOOKEEPER_CONF_DIR: /conf
    command: /zookeeper/bin/zkServer.sh start-foreground
    ports:
        - 2181:2181
        - 2888:2888
        - 3888:3888
    volumes:
        - ./conf:/zookeeper/conf
        - ./data:/data
        - ./logs:/logs
