zookeeper:
  image: jplock/zookeeper:3.4.6
  restart: always
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
kafka:
  build: .
  ports:
    - "9092:9092"
    - "7203:7203"
  env_file:
    - ./development.env
