spark:
    build: .
    environment:
        SPARK_CONF_DIR: /conf
    volumes:
        - ./conf:/conf
        - ./data:/tmp/data
    ports:
        - 51001:51001
        - 51002:51002
        - 51003:51003
        - 51004:51004
        - 51005:51005
        - 51006:51006
